name: Android CI Build

on:
  pull_request:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Spotless
        run: cd GitHubRepos && ./gradlew app:spotlessCheck

      - name: Run Lint
        run: cd GitHubRepos && ./gradlew app:lintProdDebug --stacktrace

      - name: Run Jacoco
        run: cd GitHubRepos && ./gradlew jacocoTestReport

#      TODO: add sonar scan plugin
#      - name: Code Coverage Summary
#        uses: irongut/CodeCoverageSummary@v1.2.0

      - name: Build
        run: cd GitHubRepos && ./gradlew app:assembleProdDebug

      - name: OSS Scan
        run: cd GitHubRepos && ./gradlew app:dependencyCheckAnalyze --info


