name: Android CI Build

on:
  pull_request:
  workflow_dispatch:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Spotless
        run: cd GitHubRepos && ./gradlew app:spotlessCheck

      - name: Run Lint
        run: cd GitHubRepos && ./gradlew app:lintProdDebug --stacktrace

      - name: Run Jacoco
        run: cd GitHubRepos && ./gradlew jacocoTestReport
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0-preview1'
          bundler-cache: true

      - name: Run Danger
        if: github.event_name  == 'pull_request'
        run: |
          # install danger and its dependencies using bundler
          cd GitHubRepos && gem install bundler
          # install all bundles from Gemfile
          bundle install --jobs 4 --retry 3
          # execute danger for this PR
          bundle exec danger --dangerfile=Dangerfile --danger_id=danger-pr
        env:
          # the token used by danger to report the results on the PR
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: cd GitHubRepos && ./gradlew app:assembleProdDebug

      - name: OSS Scan
        run: cd GitHubRepos && ./gradlew app:dependencyCheckAnalyze --info


