name: Check Dependency Updates
on:
  schedule:
    - cron: "37 13 * * SAT"
  workflow_dispatch:
jobs:
  dependency-updates:
    runs-on: ubuntu-latest
    steps:
      # Removed some steps for brevity
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Dependency Updates
        run: cd GitHubRepos && ./gradlew app:dependencyUpdates

      - name: Check files 1
          run: ls
      - name: Check files 2
          run: cd GitHubRepos && ls
      - name: Check files 3
          run: cd GitHubRepos/app && ls
      - name: Check files 4
          run: cd GitHubRepos/app/build && ls
      - name: Check files 5
          run: cd GitHubRepos/app/build/dependencyUpdates && ls

      - name: Log dependency update report
        run: cat GitHubRepos/app/build/dependencyUpdates/report.txt

      - name: 💌 Send email report
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/github-script@v3
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        with:
          script: |
            const scriptPath = '/./.github/scripts/dependency-update-report-mail-sender.js'
            const script = require(`${process.env.GITHUB_WORKSPACE}${scriptPath}`)
            script({ })
